name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch: 
    inputs: {}
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --blame --no-build --verbosity normal -l "console;verbosity=detailed"
    - name: Print Test Sequence
      if: failure()
      run: find . -iname Sequence_*.xml -exec cat {} \; 
